import { AvailablePlaces } from './places.enum';

export const PlacePrices = {
  [AvailablePlaces.SALVADOR]: 1,
  [AvailablePlaces.RIO]: 2,
  [AvailablePlaces.TLV_AIRPORT]: 3,
  [AvailablePlaces.TELAVIV]: 4,
  [AvailablePlaces.HAIFA]: 5,
  [AvailablePlaces.JERUSALEM]: 5,
  [AvailablePlaces.VENICE]: 7,
  [AvailablePlaces.ELECTRIC_COMPANY]: 8,
  [AvailablePlaces.MILAN]: 9,
  [AvailablePlaces.ROME]: 10,
  [AvailablePlaces.MUC_AIRPORT]: 11,
  [AvailablePlaces.FRANKFURT]: 12,
  [AvailablePlaces.MUNICH]: 13,
  [AvailablePlaces.BERLIN]: 14,
  [AvailablePlaces.SHENZHEN]: 15,
  [AvailablePlaces.BEIJING]: 16,
  [AvailablePlaces.SHANGHAI]: 17,
  [AvailablePlaces.CDG_AIRPORT]: 18,
  [AvailablePlaces.LYON]: 19,
  [AvailablePlaces.TOULOUSE]: 20,
  [AvailablePlaces.WATER_COMPANY]: 21,
  [AvailablePlaces.PARIS]: 22,
  [AvailablePlaces.LIVERPOOL]: 23,
  [AvailablePlaces.MANCHESTER]: 24,
  [AvailablePlaces.LONDON]: 25,
  [AvailablePlaces.JFK_AIRPORT]: 26,
  [AvailablePlaces.SAN_FRANCISCO]: 27,
  [AvailablePlaces.NEW_YORK]: 28,
};
